// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type RiotGame struct {
	ID        int64              `json:"id"`
	MatchID   string             `json:"match_id"`
	PlayedAt  pgtype.Timestamptz `json:"played_at"`
	Won       bool               `json:"won"`
	Analysis  pgtype.Text        `json:"analysis"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
