// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetRiotGamesByMatchIDs(ctx context.Context, matchIds []string) ([]RiotGame, error)
	GetRiotGamesInRange(ctx context.Context, arg GetRiotGamesInRangeParams) ([]RiotGame, error)
}

var _ Querier = (*Queries)(nil)
