// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: riot_games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRiotGamesByMatchIDs = `-- name: GetRiotGamesByMatchIDs :many
SELECT id, match_id, played_at, won, analysis, created_at, updated_at
FROM riot_games
WHERE match_id = ANY($1::text[])
`

func (q *Queries) GetRiotGamesByMatchIDs(ctx context.Context, matchIds []string) ([]RiotGame, error) {
	rows, err := q.db.Query(ctx, getRiotGamesByMatchIDs, matchIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RiotGame
	for rows.Next() {
		var i RiotGame
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayedAt,
			&i.Won,
			&i.Analysis,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRiotGamesInRange = `-- name: GetRiotGamesInRange :many
SELECT id, match_id, played_at, won, analysis, created_at, updated_at
FROM riot_games
WHERE played_at >= $1 AND played_at < $2
ORDER BY played_at DESC
`

type GetRiotGamesInRangeParams struct {
	PlayedAt   pgtype.Timestamptz `json:"played_at"`
	PlayedAt_2 pgtype.Timestamptz `json:"played_at_2"`
}

func (q *Queries) GetRiotGamesInRange(ctx context.Context, arg GetRiotGamesInRangeParams) ([]RiotGame, error) {
	rows, err := q.db.Query(ctx, getRiotGamesInRange, arg.PlayedAt, arg.PlayedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RiotGame
	for rows.Next() {
		var i RiotGame
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayedAt,
			&i.Won,
			&i.Analysis,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
